print("=============lua===========\n")
print("============全局========")
print(str1, type(str1))
print(str2, type(str2))
print(str3, type(str3))
print(num, type(num))
print(bool, type(bool))

print("===========表=========")
print("name is:", tab.name)
print("type is:", tab.type)
print("===========无参无返回函数=========")
fun()
print("===========有参无返回函数=========")
fun2(200, "str")
print("===========有参有返回函数=========")
str, num = fun3(200, "str")
print(str, num)
print("===========end lua=========\n")